spring.application.name=Student_Details


spring.datasource.url=jdbc:postgresql://localhost:5432/Student_Details
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Database@123

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.profiles.active=local,security


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=test@gmail.com
spring.mail.password=testpassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




app.jwt.secret=${JWT_SECRET:MySuperSecretKey12345678901234567890}

springdoc.swagger-ui.persistAuthorization=true



